version: '3'

services:
  backendapp:
    build:
      context: ./backend
    container_name: backendcontainer
    hostname: bitcoinhost
    networks:
        - bitcoin_network

  frontendapp:
    build:
      context: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backendapp
    container_name: frontendcontainer
    networks:
        - bitcoin_network

networks:
  bitcoin_network:
